# Generated by Django 4.2.3 on 2023-09-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
