# Generated by Django 4.2.3 on 2023-09-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_alter_url_link_alter_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(max_length=10),
        ),
    ]
