# Generated by Django 4.2.3 on 2023-09-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_alter_url_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField()),
                ('short_link', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
