# Generated by Django 4.2.3 on 2023-10-15 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='company',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 10, 15, 13, 43, 52, 80922, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
