# Generated by Django 4.2.3 on 2023-12-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0008_comment_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('education', models.TextField()),
                ('work_experience', models.TextField()),
                ('skills', models.TextField()),
                ('about_me', models.TextField()),
            ],
        ),
    ]
