# Generated by Django 4.2.3 on 2023-12-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0009_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('skills', models.CharField(max_length=20)),
                ('about_me', models.CharField(max_length=20)),
                ('projects', models.CharField(max_length=20)),
                ('site_code_in_github', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('features', models.CharField(max_length=20)),
                ('technologies', models.CharField(max_length=20)),
                ('goal', models.CharField(max_length=20)),
                ('project_link', models.CharField(max_length=20)),
                ('enter_link_to_shorten', models.CharField(max_length=30)),
                ('leave_feedback', models.CharField(max_length=20)),
                ('footer', models.CharField(max_length=250)),
            ],
        ),
    ]
