# Generated by Django 4.2.3 on 2023-12-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0010_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headers',
            name='email',
            field=models.CharField(max_length=20),
        ),
    ]
