# Generated by Django 4.2.3 on 2023-12-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0011_alter_headers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='about_me_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='about_me_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='description_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='description_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='education_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='education_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='enter_link_to_shorten_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='enter_link_to_shorten_uk',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='experience_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='experience_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='features_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='features_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='footer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='footer_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='goal_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='goal_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='leave_feedback_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='leave_feedback_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='name_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='phone_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='phone_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='project_link_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='project_link_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='projects_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='projects_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='site_code_in_github_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='site_code_in_github_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='skills_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='skills_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='technologies_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='technologies_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='about_me_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='about_me_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='education_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='education_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experience_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experience_uk',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='headers',
            name='footer',
            field=models.TextField(),
        ),
    ]
