# Generated by Django 4.2.3 on 2023-12-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0012_headers_about_me_en_headers_about_me_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='resume_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='resume_uk',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
