# Generated by Django 4.2.3 on 2023-12-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0013_headers_resume_en_headers_resume_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='date_of_birth_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='date_of_birth_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='email_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='email_uk',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
