# Generated by Django 4.2.3 on 2023-12-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0014_headers_date_of_birth_en_headers_date_of_birth_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='change_language',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
