# Generated by Django 4.2.3 on 2023-12-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0016_remove_headers_about_me_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='about_me_en',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='about_me_uk',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education_en',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education_uk',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills_en',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills_uk',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_experience_en',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_experience_uk',
        ),
    ]
