# Generated by Django 4.2.3 on 2024-01-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0018_headers_about_me_en_headers_about_me_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='technologies',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='technologies_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='technologies_uk',
            field=models.TextField(null=True),
        ),
    ]
