# Generated by Django 4.2.3 on 2024-01-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0019_resume_description_resume_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='reduce',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headers',
            name='reduce_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='reduce_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='submit_comment',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headers',
            name='submit_comment_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='submit_comment_uk',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
