# Generated by Django 4.2.3 on 2024-01-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0020_headers_reduce_headers_reduce_en_headers_reduce_uk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('text', models.TextField()),
                ('ciphertext', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='headers',
            name='enter_link_to_shorten',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='headers',
            name='enter_link_to_shorten_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='headers',
            name='enter_link_to_shorten_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
