# Generated by Django 4.2.3 on 2024-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0021_encryption_alter_comment_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='encrypt',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headers',
            name='key',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headers',
            name='message',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headers',
            name='text_encryption',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='encrypt_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
