# Generated by Django 4.2.3 on 2024-01-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0024_headers_actions_headers_actions_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='company',
            field=models.CharField(default=0, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headers',
            name='company_en',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='company_uk',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
