# Generated by Django 4.2.3 on 2024-01-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0025_headers_company_headers_company_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='shortened_link',
            field=models.CharField(default=0, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headers',
            name='shortened_link_en',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='headers',
            name='shortened_link_uk',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
